language:
- node_js
node_js:
   - '6.10.2'
services:
 - mongodb
before_script:
- npm install gulp --save-dev
- npm install mocha --save-dev
- npm install chai --save-dev
- npm install express --save-dev
- npm install fs --save-dev
- npm install supertest --save-dev
- npm install gulp-mocha --save-dev
- npm install xml2js --save-dev
- npm install mongodb --save-dev
- sleep 15
- mongoimport --db mydb --collection users --file data/mydb_users_65435097575.json
script:
- mocha test/testmodel2
