language:
- node_js
node_js:
   - '6.10.2'
services:
 - mongodb
before_script:
- npm install gulp --save-dev
- npm install mocha --save-dev
- npm install chai --save-dev
- npm install express --save-dev
- npm install fs --save-dev
- npm install supertest --save-dev
- npm install gulp-mocha --save-dev
- npm install xml2js --save-dev
- npm install mongodb --save-dev
- npm install codecov --save-dev
- mongoimport --db mydb --collection users --file data/mydb_users_65435097575.json
- sleep 15
- codecov --token=:adb91ff4-fb9e-4458-810c-6df77b3e2a5b
- sleep 5
after_success:
  - ./codecov -e TRAVIS_NODE_VERSION -f coverage/coverage.json
script:
- mocha test/testmodel2
- istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec

